# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

shared: &shared
  steps:
    - checkout

    - run:
        name: Install dependencies
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - run:
        name: Run tests
        command: |
          bundle exec rspec --color --require spec_helper spec --format progress

jobs:
  "rubocop":
    docker:
      - image: circleci/ruby:2.6.1-node-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: RuboCop
          command: |
            bundle exec rubocop
  "ruby-23":
    <<: *shared
    docker:
      - image: circleci/ruby:2.3.8-node-browsers
  "ruby-24":
    <<: *shared
    docker:
      - image: circleci/ruby:2.4.5-node-browsers
  "ruby-25":
    <<: *shared
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
  "ruby-26":
    <<: *shared
    docker:
      - image: circleci/ruby:2.6.1-node-browsers
  "jruby-91":
    <<: *shared
    docker:
      - image: circleci/jruby:9.1-jdk
        environment:
          JRUBY_OPTS: "--debug"
  "jruby-92":
    <<: *shared
    docker:
      - image: circleci/jruby:9.2-jdk
        environment:
          JRUBY_OPTS: "--debug"

workflows:
  version: 2
  build:
    jobs:
      - rubocop
      - "ruby-23":
          requires:
            - rubocop
      - "ruby-24":
          requires:
            - rubocop
      - "ruby-25":
          requires:
            - rubocop
      - "ruby-26":
          requires:
            - rubocop
      - "jruby-91":
          requires:
            - rubocop
      - "jruby-92":
          requires:
            - rubocop
